import React from "react";
import {Metadata} from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: 'NotFoundPage',
    description: 'Generated by DSD Media',
}

interface INotFoundPage {

}

const NotFoundPage = async ({}: INotFoundPage) => {

    return (
        <section className="grid h-screen place-items-center px-6 py-24 sm:py-32 lg:px-8">
            <div className="text-center">
                <h1 className="text-base font-semibold">404</h1>
                <h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Seite nicht gefunden</h2>
                <p className="mt-6 text-base leading-7">
                    Entschuldigung, wir konnten die gesuchte Seite nicht finden.
                </p>
                <div className="mt-10 flex items-center justify-center gap-x-6">
                    <Link href="/">Zur Startseite</Link>
                </div>
            </div>
        </section>
    );
}

export default NotFoundPage;